// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNode = "node"

// Node mapped from table <node>
type Node struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       int64          `gorm:"column:uid;not null" json:"uid"`
	Type      int32          `gorm:"column:type;not null;default:2" json:"type"`
	ParentID  *int64         `gorm:"column:parent_id" json:"parent_id"`
	Title     string         `gorm:"column:title;not null" json:"title"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	Path      string         `gorm:"column:path;not null" json:"path"`
	Sort      int32          `gorm:"column:sort;not null" json:"sort"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Node's table name
func (*Node) TableName() string {
	return TableNameNode
}
