pgsql:
  host: localhost
  user: admin
  pwd: 123456
  port: 5433
service:
  auth:
    grpc: localhost
    port: 9900
  post:
    grpc: localhost
    port: 9910
  user:
    grpc: localhost
    port: 9920
minio:
  endpoint: "localhost:10100"
  access_key: "admin"
  secret_key: "admin123456"
  external_url: "http://localhost:10100"