pgsql:
  host: pgsql
  user: admin
  pwd: 123456
  port: 5432
service:
  auth:
    grpc: auth
    port: 9900
  post:
    grpc: post
    port: 9910
  user:
    grpc: user
    port: 9920
minio:
  endpoint: "minio:10000"       # docker 内部用服务名
  access_key: "admin"
  secret_key: "admin123456"
  external_url: "http://localhost:10000"