pgsql:
  host: pgsql
  user: admin
  pwd: 123456
  port: 5432
service:
  auth:
    grpc: auth
    port: 9900
  post:
    grpc: post
    port: 9910
  user:
    grpc: user
    port: 9920
minio:
  endpoint: "minio:10000"       # docker 内部用服务名
  access_key: "admin"
  secret_key: "admin123456"
  external_url: "http://localhost:10000"
jwt:
  secret_key: a3f1b7c9e2d4f6a8b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3