// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int64          `gorm:"column:uid;not null" json:"uid"`
	Title        string         `gorm:"column:title;not null" json:"title"`
	Content      string         `gorm:"column:content;not null" json:"content"`
	IsTopped     bool           `gorm:"column:is_topped;not null" json:"is_topped"`
	IsDraft      bool           `gorm:"column:is_draft;not null" json:"is_draft"`
	PostType     int16          `gorm:"column:post_type;not null;default:1" json:"post_type"`
	LikeCount    int32          `gorm:"column:like_count;not null" json:"like_count"`
	CommentCount int32          `gorm:"column:comment_count;not null" json:"comment_count"`
	CollectCount int32          `gorm:"column:collect_count;not null" json:"collect_count"`
	ViewCount    int32          `gorm:"column:view_count;not null" json:"view_count"`
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
