pgsql:
  host: localhost
  user: admin
  pwd: 123456
  port: 5433
service:
  auth:
    grpc: localhost
    port: 9900
  post:
    grpc: localhost
    port: 9910
  user:
    grpc: localhost
    port: 9920
minio:
  endpoint: "localhost:10100"
  access_key: "admin"
  secret_key: "admin123456"
  external_url: "http://localhost:10100"
jwt:
  secret_key: a3f1b7c2e2d9f6a8b0c1d2e3f4a5b6c7d8e9f1a1b3c3d4e5f6a7b8c9d0e1f2a3