// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID      int64  `gorm:"column:uid;not null;comment:用户唯一标识" json:"uid"`       // 用户唯一标识
	Account  string `gorm:"column:account;not null;comment:账号" json:"account"`   // 账号
	Password string `gorm:"column:password;not null;comment:密码" json:"password"` // 密码
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
